//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptuxiaki.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ptuxiaki.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1300740398_exit {
            get {
                object obj = ResourceManager.GetObject("1300740398_exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1300740398_exit1 {
            get {
                object obj = ResourceManager.GetObject("1300740398_exit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1300740457_exit {
            get {
                object obj = ResourceManager.GetObject("1300740457_exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1300790450_3floppy_unmount {
            get {
                object obj = ResourceManager.GetObject("1300790450_3floppy_unmount", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1300792367_add {
            get {
                object obj = ResourceManager.GetObject("1300792367_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1301087973_Search_Male_User {
            get {
                object obj = ResourceManager.GetObject("1301087973_Search-Male-User", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1301088130_system_software_update {
            get {
                object obj = ResourceManager.GetObject("1301088130_system-software-update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1301088199_network_zoom {
            get {
                object obj = ResourceManager.GetObject("1301088199_network_zoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1301088225_add_group {
            get {
                object obj = ResourceManager.GetObject("1301088225_add_group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1301332279_network_add {
            get {
                object obj = ResourceManager.GetObject("1301332279_network_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1301332334_add_to_favorites {
            get {
                object obj = ResourceManager.GetObject("1301332334_add-to-favorites", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1301333133_delete_user {
            get {
                object obj = ResourceManager.GetObject("1301333133_delete_user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1301333202_network_delete {
            get {
                object obj = ResourceManager.GetObject("1301333202_network_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1301407111_kde_folder_saved_search {
            get {
                object obj = ResourceManager.GetObject("1301407111_kde-folder-saved-search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1301407580_interact {
            get {
                object obj = ResourceManager.GetObject("1301407580_interact", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1301407902_Delete {
            get {
                object obj = ResourceManager.GetObject("1301407902_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1301507896_Windows_Turn_Off {
            get {
                object obj = ResourceManager.GetObject("1301507896_Windows_Turn_Off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1301510751_success {
            get {
                object obj = ResourceManager.GetObject("1301510751_success", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1301512519_fileclose {
            get {
                object obj = ResourceManager.GetObject("1301512519_fileclose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1301512519_fileclose1 {
            get {
                object obj = ResourceManager.GetObject("1301512519_fileclose1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1301942878_binoculars_128 {
            get {
                object obj = ResourceManager.GetObject("1301942878_binoculars_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1304356322_folder_updates {
            get {
                object obj = ResourceManager.GetObject("1304356322_folder_updates", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1304615470_edit {
            get {
                object obj = ResourceManager.GetObject("1304615470_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1304616548_ok {
            get {
                object obj = ResourceManager.GetObject("1304616548_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1313244897_1 {
            get {
                object obj = ResourceManager.GetObject("1313244897_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1315929804_user_group_new {
            get {
                object obj = ResourceManager.GetObject("1315929804_user-group-new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1316450423_Orb_minus {
            get {
                object obj = ResourceManager.GetObject("1316450423_Orb_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1316963946_change_password {
            get {
                object obj = ResourceManager.GetObject("1316963946_change_password", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1317056395_Stats {
            get {
                object obj = ResourceManager.GetObject("1317056395_Stats", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1317056515_column_chart {
            get {
                object obj = ResourceManager.GetObject("1317056515_column_chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1317056558_pie_chart {
            get {
                object obj = ResourceManager.GetObject("1317056558_pie_chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1317237432_old_edit_undo {
            get {
                object obj = ResourceManager.GetObject("1317237432_old-edit-undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1317240698_10 {
            get {
                object obj = ResourceManager.GetObject("1317240698_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1317241047_7 {
            get {
                object obj = ResourceManager.GetObject("1317241047_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1317560891_Help {
            get {
                object obj = ResourceManager.GetObject("1317560891_Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1317560958_help_contents {
            get {
                object obj = ResourceManager.GetObject("1317560958_help-contents", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1317561048_stop {
            get {
                object obj = ResourceManager.GetObject("1317561048_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fonto {
            get {
                object obj = ResourceManager.GetObject("Fonto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fonto1 {
            get {
                object obj = ResourceManager.GetObject("Fonto1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fonto2 {
            get {
                object obj = ResourceManager.GetObject("Fonto2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_1_ {
            get {
                object obj = ResourceManager.GetObject("search(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_2_ {
            get {
                object obj = ResourceManager.GetObject("search(2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap system_software_update {
            get {
                object obj = ResourceManager.GetObject("system_software_update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
